from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def export_basic_pdf(output_path: Path, title: str, watermark_text: str = "") -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf = canvas.Canvas(str(output_path), pagesize=A4)
    width, height = A4

    if watermark_text:
        pdf.saveState()
        pdf.setFont("Helvetica", 42)
        pdf.setFillGray(0.85)
        pdf.translate(width / 2, height / 2)
        pdf.rotate(35)
        pdf.drawCentredString(0, 0, watermark_text)
        pdf.restoreState()

    pdf.setFont("Helvetica", 16)
    pdf.drawString(60, height - 80, title)
    pdf.setFont("Helvetica", 10)
    pdf.drawString(60, height - 110, "Generated by interface manager.")
    pdf.showPage()
    pdf.save()
    return output_path
