import json
import subprocess
from shutil import copy2
from pathlib import Path
from tempfile import TemporaryDirectory

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

import json

from app.models import ApiInterface, ApiParameter, InterfaceDirection, ParameterKind


class PdfConversionError(RuntimeError):
    pass


def export_basic_pdf(output_path: Path, title: str, watermark_text: str = "") -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf = canvas.Canvas(str(output_path), pagesize=A4)
    width, height = A4

    if watermark_text:
        pdf.saveState()
        pdf.setFont("Helvetica", 42)
        pdf.setFillGray(0.85)
        pdf.translate(width / 2, height / 2)
        pdf.rotate(35)
        pdf.drawCentredString(0, 0, watermark_text)
        pdf.restoreState()

    pdf.setFont("Helvetica", 16)
    pdf.drawString(60, height - 80, title)
    pdf.setFont("Helvetica", 10)
    pdf.drawString(60, height - 110, "Generated by interface manager.")
    pdf.showPage()
    pdf.save()
    return output_path


def export_pdf_document(
    output_path: Path,
    interfaces: list[ApiInterface],
    request_examples: dict[int, dict],
    response_examples: dict[int, dict],
    parameters_by_interface: dict[int, list[ApiParameter]],
    watermark_text: str = "",
    source_docx_path: Path | None = None,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if source_docx_path and _convert_docx_to_pdf(source_docx_path, output_path):
        return output_path
    raise PdfConversionError("PDF 转换失败：请安装 Microsoft Word 或 LibreOffice 后重试。")


def _convert_docx_to_pdf(source_docx_path: Path, output_path: Path) -> bool:
    source_docx_path = source_docx_path.resolve()
    output_path = output_path.resolve()
    converters = [
        _word_com_convert,
        [
            "soffice",
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(output_path.parent.resolve()),
            str(source_docx_path.resolve()),
        ],
        [
            "libreoffice",
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(output_path.parent.resolve()),
            str(source_docx_path.resolve()),
        ],
    ]
    for command in converters:
        if not command:
            continue
        try:
            if callable(command):
                if command(source_docx_path, output_path):
                    return True
                continue
            result = subprocess.run(command, capture_output=True, text=True, timeout=60)
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
        if result.returncode != 0:
            continue
        converted = output_path.parent / f"{source_docx_path.stem}.pdf"
        if converted.exists():
            if converted.resolve() != output_path.resolve():
                converted.replace(output_path)
            return True
    return False


def _word_com_convert(source_docx_path: Path, output_path: Path) -> bool:
    with TemporaryDirectory(prefix="eap_pdf_") as tmp_dir:
        temp_docx = Path(tmp_dir) / "source.docx"
        temp_pdf = Path(tmp_dir) / "source.pdf"
        copy2(source_docx_path, temp_docx)
        command = _word_com_command(temp_docx, temp_pdf, source_docx_path.name)
        try:
            result = subprocess.run(command, capture_output=True, text=True, timeout=60)
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False
        if result.returncode != 0 or not temp_pdf.exists():
            return False
        output_path.parent.mkdir(parents=True, exist_ok=True)
        copy2(temp_pdf, output_path)
        return output_path.exists()


def _word_com_command(source_docx_path: Path, output_path: Path, display_filename: str = "") -> list[str] | None:
    script = (
        "& { param($sourcePath, $outputPath, $displayFilename)"
        "$ErrorActionPreference = 'Stop';"
        "$word = New-Object -ComObject Word.Application;"
        "$word.Visible = $false;"
        "$doc = $null;"
        "try {"
        "  $doc = $word.Documents.Open([string]$sourcePath, $false, $true, $false);"
        "  if ($null -eq $doc) { throw 'Word failed to open source document.' }"
        "  $doc.Fields.Update() | Out-Null;"
        "  foreach ($toc in $doc.TablesOfContents) { $toc.Update() | Out-Null; }"
        "  if ($displayFilename) {"
        "    foreach ($field in $doc.Fields) {"
        "      if ($field.Code.Text -match 'FILENAME') { $field.Result.Text = $displayFilename }"
        "    }"
        "  }"
        "  $doc.Repaginate();"
        "  $doc.ExportAsFixedFormat([string]$outputPath, 17);"
        "  $doc.Close($false);"
        "} finally {"
        "  if ($null -ne $doc) { try { $doc.Close($false) } catch {} }"
        "  $word.Quit();"
        "}"
        "}"
    )
    return [
        "powershell",
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-Command",
        script,
        str(source_docx_path.resolve()),
        str(output_path.resolve()),
        display_filename,
    ]


def build_pdf_sections(
    interfaces: list[ApiInterface],
    request_examples: dict[int, dict],
    response_examples: dict[int, dict],
    parameters_by_interface: dict[int, list[ApiParameter]],
) -> list[str]:
    lines: list[str] = []
    _append_direction(lines, interfaces, InterfaceDirection.EQP_TO_EAP, "EQP -> EAP 接口", request_examples, response_examples, parameters_by_interface)
    _append_direction(lines, interfaces, InterfaceDirection.EAP_TO_EQP, "EAP -> EQP 接口", request_examples, response_examples, parameters_by_interface)
    return lines


def _append_direction(
    lines: list[str],
    interfaces: list[ApiInterface],
    direction: InterfaceDirection,
    heading: str,
    request_examples: dict[int, dict],
    response_examples: dict[int, dict],
    parameters_by_interface: dict[int, list[ApiParameter]],
) -> None:
    lines.extend([f"# {heading}", ""])
    for item in interfaces:
        if item.direction != direction:
            continue
        key = item.id or 0
        parameters = parameters_by_interface.get(key, [])
        lines.extend(
            [
                f"## {item.code} {item.name}",
                f"接口名称: {item.api_name}",
                f"调用方: {item.caller}",
                f"提供方: {item.provider}",
                f"版本: {item.version}",
                f"接口服务描述: {item.service_description or '-'}",
                "### 请求参数",
                "字段名 | 类型 | 必填 | 数组 | 说明",
                *_parameter_lines(parameters, ParameterKind.REQUEST),
                "### 响应参数",
                "字段名 | 类型 | 必填 | 数组 | 说明",
                *_parameter_lines(parameters, ParameterKind.RESPONSE),
                "### 日志范例",
                "请求日志范例",
                item.request_log_example or json.dumps(request_examples.get(key, {}), ensure_ascii=False, indent=2),
                "响应日志范例",
                item.response_log_example or json.dumps(response_examples.get(key, {}), ensure_ascii=False, indent=2),
                "",
            ]
        )


def _parameter_lines(parameters: list[ApiParameter], kind: ParameterKind) -> list[str]:
    items = [
        parameter
        for parameter in sorted(parameters, key=lambda item: (item.sort_order, item.id or 0))
        if parameter.kind == kind
    ]
    if not items:
        return ["无"]
    return [
        f"{_parameter_sequence(item)} {item.field_name} | {item.data_type} | {'是' if item.required else '否'} | {'是' if item.is_array else '否'} | {item.description}"
        for item in items
    ]


def _parameter_sequence(parameter: ApiParameter) -> str:
    if not parameter.enum_options:
        return ""
    try:
        data = json.loads(parameter.enum_options)
    except json.JSONDecodeError:
        return ""
    sequence = data.get("sequence") if isinstance(data, dict) else ""
    return sequence if isinstance(sequence, str) else ""


class _PdfTextWriter:
    def __init__(self, pdf: canvas.Canvas, width: float, height: float, watermark_text: str) -> None:
        self.pdf = pdf
        self.width = width
        self.height = height
        self.watermark_text = watermark_text
        self.y = height - 60
        self._draw_watermark()

    def write_title(self, text: str) -> None:
        self._ensure_space(28)
        self.pdf.setFont("Helvetica", 16)
        self.pdf.drawString(50, self.y, _safe_pdf_text(text))
        self.y -= 28

    def write_heading(self, text: str, level: int) -> None:
        self._ensure_space(24)
        size = 14 if level == 1 else 12 if level == 2 else 10
        self.pdf.setFont("Helvetica-Bold", size)
        self.pdf.drawString(50, self.y, _safe_pdf_text(text))
        self.y -= 22

    def write_line(self, text: str) -> None:
        self.pdf.setFont("Helvetica", 9)
        for line in str(text).splitlines() or [""]:
            for chunk in _wrap_text(line, 110):
                self._ensure_space(14)
                self.pdf.drawString(50, self.y, _safe_pdf_text(chunk))
                self.y -= 14

    def write_blank(self) -> None:
        self.y -= 10

    def save(self) -> None:
        self.pdf.showPage()
        self.pdf.save()

    def _ensure_space(self, required: int) -> None:
        if self.y < 60 + required:
            self.pdf.showPage()
            self.y = self.height - 60
            self._draw_watermark()

    def _draw_watermark(self) -> None:
        if not self.watermark_text:
            return
        self.pdf.saveState()
        self.pdf.setFont("Helvetica", 42)
        self.pdf.setFillGray(0.85)
        self.pdf.translate(self.width / 2, self.height / 2)
        self.pdf.rotate(35)
        self.pdf.drawCentredString(0, 0, _safe_pdf_text(self.watermark_text))
        self.pdf.restoreState()


def _wrap_text(text: str, max_chars: int) -> list[str]:
    if len(text) <= max_chars:
        return [text]
    return [text[index : index + max_chars] for index in range(0, len(text), max_chars)]


def _safe_pdf_text(text: str) -> str:
    return text.encode("latin-1", errors="replace").decode("latin-1")
